POST /game/new-session HTTP/1.1
Host: lynrummy.com
Cookie: gopher_uid=p2.1789732801.JQe2xbtKNu4Ie7fkr4jBC50RH_RYdoQnr1S3tHAGoiw
Content-Type: text/plain
Content-Length: 5
Connection: close

state